services:
  mongo:
    image: mongo:latest
    container_name: mindigo-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mindigo
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: local-mongo-express
    restart: always
    ports:
      - "9090:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mindigo
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_BASICAUTH_USERNAME: mindigo
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    depends_on:
      - mongo

volumes:
  mongo_data: