spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  application:
    name: game-service

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG