spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  application:
    name: routine-service






#server:
#  port: 8080
#
#spring:
#  jackson:
#    serialization:
#      write-dates-as-timestamps: false
#    time-zone: UTC
#
#logging:
#  level:
#    com.healthcare.routine: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics
#  endpoint:
#    health:
#      show-details: always