spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - name: JwtAuth
            - id: assessment-service
              uri: lb://assessment-service
              predicates:
                - Path=/api/v1/assessment/**
            - id: mail-service
              uri: lb://mail-service
              predicates:
                - Path=/api/v1/mail/**
            - id: game-service
              uri: lb://game-service
              predicates:
                - Path=/api/v1/game/**
              filters:
                - name: JwtAuth
            - id: file-server
              uri: lb://file-server
              predicates:
                - Path=/api/v1/file/**
            - id: content-service
              uri: lb://content-service
              predicates:
                - Path=/api/v1/content/**
              filters:
                - name: JwtAuth
            - id: routine-service
              uri: lb://routine-service
              predicates:
                - Path=/api/v1/routines/**
              filters:
                - name: JwtAuth
            - id: admin-service
              uri: lb://admin-service
              predicates:
                - Path=/api/v1/admin/**
              filters:
                - name: JwtAuth
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: health
