eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${random.uuid}

server:
  port: ${FILE_SERVER_PORT:8085}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}
  bucket: ${SUPABASE_BUCKET}

management:
  endpoints:
    web:
      exposure:
        include: health